name: Latest CSV
on: 
  workflow_dispatch:
  schedule:
    - cron:  '01 00 * * *'

jobs:
  build:
    name: Latest CSV
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Write CSV
      run:  ./latestRelease.sh | tee releases_$(date '+%Y%m%d_%H%M').csv
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MarketReleases
        path: releases_*.csv
