name: Latest status report
on: 
  workflow_dispatch:
  schedule:
    - cron:  '01 00 * * *'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Checking status for market products
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Write CSV
      run:  ./latestRelease.sh | tee MarketUp2DateStatus_$(date '+%Y%m%d_%H%M').csv
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MarketUp2DateStatus
        path: MarketUp2DateStatus_*.csv
