name: Raise Market Products

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'github repository name (e.g. hubspot-connector) or blank for all projects of the axonivy-market org'
        required: false
      version:
        description: 'Version to raise (e.g. 9.4.0)'
        required: true
        default: '9.4.0-SNAPSHOT'
      engineUrl:
        description: 'Axon Ivy Engine URL'
        required: true
        default: 'https://developer.axonivy.com/permalink/9.4.0/axonivy-engine.zip'

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Configure Git
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Raise Products
        run: |
          export engineUrl=${{ github.event.inputs.engineUrl }}
          ./raise-all-market-products.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.product }}
        shell: bash
