name: Raise Market Products
run-name: Raise ${{ inputs.product }} by @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'github repository name (e.g. alfresco-connector) or blank for all projects of the axonivy-market org'
        required: false
      version:
        description: 'Snaphsot version to raise (e.g. "12.0.0-SNAPSHOT")'
        required: true
        default: '12.0.0-SNAPSHOT'
      engineUrl:
        description: 'Axon Ivy Engine URL'
        required: true
        default: 'https://developer.axonivy.com/permalink/12.0.0/axonivy-engine.zip'

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Raise Products
        run: |
          export engineUrl=${{ inputs.engineUrl }}
          export IVY_JAVA_HOME=$JAVA_HOME_21_X64
          echo "workDir=$(pwd)" >> $GITHUB_ENV
          ./raise-all-market-products.sh ${{ inputs.version }} ${{ inputs.product }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show migrated repositories
        if: ${{ inputs.product == '' }} 
        run: cat ${workDir}/migrated-repos.txt
        shell: bash
