name: Raise Market Products
run-name: Raise ${{ inputs.product }} by @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'github repository name (e.g. alfresco-connector) or blank for all projects of the axonivy-market org'
        required: false
        default: 'migrate-14.0'
      version:
        description: 'Snaphsot version to raise (e.g. "14.0.0-SNAPSHOT")'
        required: true
        default: '14.0.0-SNAPSHOT'
      engineUrl:
        description: 'Axon Ivy Engine URL'
        required: true
        default: 'https://developer.axonivy.com/permalink/sprint/axonivy-engine.zip'
      migrateToLatestLTSVersion:
        description: 'Migrate current source code to the latest LTS version (e.g. 14.0.0). If the value is false (migrate to latest dev version e.g. 13.0, 15.0,...), the source code will be clone into below releaseBranch before raising the version.'
        required: false
        type: boolean
        default: false
      releaseBranch:
        description: 'Name of the release branch to create (e.g. "release/14.0"). Only used when "migrateToLatestLTSVersion" is false.'
        required: false
        default: 'release/14.0'
      buildPluginVersion:
        description: 'Version of the build plugin'
        required: false
        default: ''
      testerVersion:
        description: 'Version of the tester plugin'
        required: false
        default: ''

permissions:
  contents: read
  pull-requests: write

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo ${{ env.GH_TOKEN2 }} > token.sh
          gh auth login --with-token < token.sh
          gh auth setup-git
        env:
          GH_TOKEN2: ${{ secrets.GH }}

      - name: Raise Products
        run: |
          export engineUrl=${{ inputs.engineUrl }}
          export releaseBranch=${{ inputs.migrateToLatestLTSVersion == false && '' || inputs.releaseBranch }}
          export migrateToLatestLTSVersion=${{ inputs.migrateToLatestLTSVersion }}
          export buildPluginVersion=${{ inputs.buildPluginVersion }}
          export testerVersion=${{ inputs.testerVersion }}
          echo "workDir=$(pwd)" >> $GITHUB_ENV
          ./raise-all-market-products.sh ${{ inputs.version }} ${{ inputs.product }}
        shell: bash

      - name: Show migrated repositories
        if: ${{ inputs.product == '' }} 
        run: cat ${workDir}/migrated-repos.txt
        shell: bash
