name: Raise Market Products

on: 
  workflow_dispatch:
    inputs:
      product:
        description: 'Axon Ivy product github name (none for all)'
        required: false
      version:
        description: 'Version to raise (e.g. 9.4.0)'
        required: true
      engineUrl:
        description: 'Axon Ivy Engine URL'
        required: true
        default: 'https://developer.axonivy.com/permalink/9.4.0/axonivy-engine.zip'

jobs:
  raise-products:
    runs-on: ubuntu-latest

    steps:
      - name: Set engine download URL
        run: export engineUrl=${{ github.event.inputs.engineUrl }}
        shell: bash

      - name: Raise Products
        run: ./raise-all-market-products.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.product }}
        shell: bash
